readthedocs/builds/urls.py
from django.conf.urls import url

from .views import (
    BuildList, BuildDetail, builds_redirect_detail, builds_redirect_list,
)


urlpatterns = [
    url(r'^(?P<project_slug>[-\w]+)/(?P<pk>\d+)/$',
        builds_redirect_detail,
        name='old_builds_detail'),

    url(r'^(?P<project_slug>[-\w]+)/$',
        builds_redirect_list,
        name='old_builds_project_list'),
]

readthedocs/donate/urls.py
from django.conf.urls import url, include

from .views import DonateCreateView, DonateListView, DonateSuccessView
from .views import PayAdsView, PaySuccess, PromoDetailView
from .views import click_proxy, view_proxy


urlpatterns = [
    url(r'^$', DonateListView.as_view(), name='donate'),
    url(r'^pay/$', PayAdsView.as_view(), name='pay_ads'),
    url(r'^pay/success/$', PaySuccess.as_view(), name='pay_success'),
    url(r'^report/(?P<promo_slug>.+)/$', PromoDetailView.as_view(), name='donate_promo_detail'),
    url(r'^contribute/$', DonateCreateView.as_view(), name='donate_add'),
    url(r'^contribute/thanks$', DonateSuccessView.as_view(), name='donate_success'),
    url(r'^view/(?P<promo_id>\d+)/(?P<hash>.+)/$', view_proxy, name='donate_view_proxy'),
    url(r'^click/(?P<promo_id>\d+)/(?P<hash>.+)/$', click_proxy, name='donate_click_proxy'),
]

readthedocs/gold/urls.py
"""Gold subscription URLs"""

from django.conf.urls import url

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX


urlpatterns = [
    url(r'^$', views.DetailGoldSubscription.as_view(), name='gold_detail'),
    url(r'^subscription/$', views.UpdateGoldSubscription.as_view(),
        name='gold_subscription'),
    url(r'^cancel/$', views.DeleteGoldSubscription.as_view(), name='gold_cancel'),
    url(r'^projects/$', views.projects, name='gold_projects'),
    url((r'^projects/remove/(?P<project_slug>{project_slug})/$'
         .format(project_slug=PROJECT_SLUG_REGEX)),
        views.projects_remove,
        name='gold_projects_remove'),
]

readthedocs/urls.py
# pylint: disable=missing-docstring

from operator import add

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from tastypie.api import Api

from readthedocs.api.base import (ProjectResource, UserResource,
                                  VersionResource, FileResource)
from readthedocs.core.urls import docs_urls, core_urls, deprecated_urls
from readthedocs.core.views import HomepageView, SupportView
from readthedocs.search import views as search_views


v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(ProjectResource())
v1_api.register(VersionResource())
v1_api.register(FileResource())

admin.autodiscover()

handler500 = 'readthedocs.core.views.server_error'
handler404 = 'readthedocs.core.views.server_error_404'

basic_urls = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^support/', SupportView.as_view(), name='support'),
    url(r'^security/', TemplateView.as_view(template_name='security.html')),
]

rtd_urls = [
    url(r'^bookmarks/', include('readthedocs.bookmarks.urls')),
    url(r'^search/$', search_views.elastic_search, name='search'),
    url(r'^dashboard/', include('readthedocs.projects.urls.private')),
    url(r'^profiles/', include('readthedocs.profiles.urls.public')),
    url(r'^accounts/', include('readthedocs.profiles.urls.private')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^notifications/', include('readthedocs.notifications.urls')),
    # For redirects
    url(r'^builds/', include('readthedocs.builds.urls')),
]

project_urls = [
    url(r'^projects/', include('readthedocs.projects.urls.public')),
]

api_urls = [
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/', include('readthedocs.restapi.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^websupport/', include('readthedocs.comments.urls')),
]

i18n_urls = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    url(r'^admin/', include(admin.site.urls)),
]

debug_urls = add(
    [
        url('style-catalog/$',
            TemplateView.as_view(template_name='style_catalog.html')),
    ],
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

# Export URLs
groups = [basic_urls, rtd_urls, project_urls, api_urls, core_urls, i18n_urls,
          deprecated_urls]

if 'readthedocs.donate' in settings.INSTALLED_APPS:
    # Include donation URL's
    groups.append([
        url(r'^sustainability/', include('readthedocs.donate.urls')),
        url(r'^accounts/gold/', include('readthedocs.gold.urls')),
    ])
if not getattr(settings, 'USE_SUBDOMAIN', False) or settings.DEBUG:
    groups.insert(0, docs_urls)
if getattr(settings, 'ALLOW_ADMIN', True):
    groups.append(admin_urls)
if getattr(settings, 'DEBUG', False):
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

readthedocs/bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _, ugettext

from readthedocs.builds.models import Version
from readthedocs.projects.models import Project


class Bookmark(models.Model):
    user = models.ForeignKey(User, verbose_name=_('User'),
                             related_name='bookmarks')
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='bookmarks')
    version = models.ForeignKey(Version, verbose_name=_('Version'),
                                related_name='bookmarks')
    page = models.CharField(_('Page'), max_length=255)

    date = models.DateTimeField(_('Date'), auto_now_add=True)
    url = models.CharField(_('URL'), max_length=255, null=True, blank=True)

    class Meta:
        ordering = ['-date']
        unique_together = ('user', 'project', 'version', 'page')

    def __unicode__(self):
        return ugettext(u"Bookmark %(url)s for %(user)s (%(pk)s)") % {
            'url': self.url,
            'user': self.user,
            'pk': self.pk,
        }

    def get_absolute_url(self):
        return self.url

readthedocs/builds/forms.py
from django import forms

from readthedocs.builds.models import VersionAlias, Version
from readthedocs.projects.models import Project
from readthedocs.core.utils import trigger_build


class AliasForm(forms.ModelForm):

    class Meta:
        model = VersionAlias
        fields = (
            'project',
            'from_slug',
            'to_slug',
            'largest',
        )

    def __init__(self, instance=None, *args, **kwargs):
        super(AliasForm, self).__init__(instance=instance, *args, **kwargs)
        if instance:
            self.fields['project'].queryset = (Project.objects
                                               .filter(pk=instance.project.pk))


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = ['active', 'privacy_level', 'tags']

    def save(self, *args, **kwargs):
        obj = super(VersionForm, self).save(*args, **kwargs)
        if obj.active and not obj.built and not obj.uploaded:
            trigger_build(project=obj.project, version=obj)
        return obj

readthedocs/core/forms.py
import logging

from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from django import forms
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _

from .models import UserProfile

log = logging.getLogger(__name__)


class UserProfileForm(forms.ModelForm):
    first_name = CharField(label=_('First name'), required=False)
    last_name = CharField(label=_('Last name'), required=False)

    class Meta:
        model = UserProfile
        # Don't allow users edit someone else's user page,
        fields = ['first_name', 'last_name', 'homepage']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except:
            pass

    def save(self, *args, **kwargs):
        first_name = self.cleaned_data.pop('first_name', None)
        last_name = self.cleaned_data.pop('last_name', None)
        profile = super(UserProfileForm, self).save(*args, **kwargs)
        if kwargs.get('commit', True):
            user = profile.user
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        return profile


class FacetField(forms.MultipleChoiceField):

    """
    For filtering searches on a facet.

    Has validation for the format of facet values.
    """

    def valid_value(self, value):
        """
        Although this is a choice field, no choices need to be supplied.

        Instead, we just validate that the value is in the correct format
        for facet filtering (facet_name:value)
        """
        if ":" not in value:
            return False
        return True


class FacetedSearchForm(SearchForm):

    """
    Supports fetching faceted results with a corresponding query.

    `facets`
        A list of facet names for which to get facet counts
    `models`
        Limit the search to one or more models
    """

    selected_facets = FacetField(required=False)

    def __init__(self, *args, **kwargs):
        facets = kwargs.pop('facets', [])
        models = kwargs.pop('models', [])
        super(FacetedSearchForm, self).__init__(*args, **kwargs)

        for facet in facets:
            self.searchqueryset = self.searchqueryset.facet(facet)
        if models:
            self.searchqueryset = self.searchqueryset.models(*models)

    def clean_selected_facets(self):
        facets = self.cleaned_data['selected_facets']
        cleaned_facets = []
        clean = SearchQuerySet().query.clean
        for facet in facets:
            field, value = facet.split(":", 1)
            if not value:  # Ignore empty values
                continue
            value = clean(value)
            cleaned_facets.append(u'%s:"%s"' % (field, value))
        return cleaned_facets

    def search(self):
        sqs = super(FacetedSearchForm, self).search()
        for facet in self.cleaned_data['selected_facets']:
            sqs = sqs.narrow(facet)
        self.searchqueryset = sqs
        return sqs

readthedocs/bookmarks/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render_to_response
from django.views.generic import ListView, View
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
import json

from readthedocs.bookmarks.models import Bookmark
from readthedocs.projects.models import Project


# These views are CSRF exempt because of Django's CSRF middleware failing here
# https://github.com/django/django/blob/stable/1.6.x/django/middleware/csrf.py#L135-L159
# We don't have a valid referrer because we're on a subdomain


class BookmarkExistsView(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(BookmarkExistsView, self).dispatch(*args, **kwargs)

    def get(self, request):
        return HttpResponse(
            content=json.dumps(
                {'error': 'You must POST!'}
            ),
            content_type='application/json',
            status=405
        )

    def post(self, request, *args, **kwargs):
        """
        Returns:
            200 response with exists = True in json if bookmark exists.
            404 with exists = False in json if no matching bookmark is found.
            400 if json data is missing any one of: project, version, page.
        """
        post_json = json.loads(request.body)
        try:
            project = post_json['project']
            version = post_json['version']
            page = post_json['page']
        except KeyError:
            return HttpResponseBadRequest(
                content=json.dumps({'error': 'Invalid parameters'})
            )
        try:
            Bookmark.objects.get(
                project__slug=project,
                version__slug=version,
                page=page
            )
        except ObjectDoesNotExist:
            return HttpResponse(
                content=json.dumps({'exists': False}),
                status=404,
                content_type="application/json"
            )

        return HttpResponse(
            content=json.dumps({'exists': True}),
            status=200,
            content_type="application/json"
        )


class BookmarkListView(ListView):
    """ Displays all of a logged-in user's bookmarks """
    model = Bookmark

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BookmarkListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Bookmark.objects.filter(user=self.request.user)


class BookmarkAddView(View):
    """ Adds bookmarks in response to POST requests """

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(BookmarkAddView, self).dispatch(*args, **kwargs)

    def get(self, request):
        return HttpResponse(
            content=json.dumps(
                {'error': 'You must POST!'}
            ),
            content_type='application/json',
            status=405
        )

    def post(self, request, *args, **kwargs):
        """Add a new bookmark for the current user to point at
        ``project``, ``version``, ``page``, and ``url``.
        """
        post_json = json.loads(request.body)
        try:
            project_slug = post_json['project']
            version_slug = post_json['version']
            page_slug = post_json['page']
            url = post_json['url']
        except KeyError:
            return HttpResponseBadRequest(
                content=json.dumps({'error': "Invalid parameters"})
            )

        try:
            project = Project.objects.get(slug=project_slug)
            version = project.versions.get(slug=version_slug)
        except ObjectDoesNotExist:
            return HttpResponseBadRequest(
                content=json.dumps(
                    {'error': "Project or Version does not exist"}
                )
            )

        Bookmark.objects.get_or_create(
            user=request.user,
            url=url,
            project=project,
            version=version,
            page=page_slug,
        )
        return HttpResponse(
            json.dumps({'added': True}),
            status=201,
            content_type='application/json'
        )


class BookmarkRemoveView(View):
    """
    Deletes a user's bookmark in response to a POST request.
    Renders a delete? confirmation page in response to a GET request.
    """

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(BookmarkRemoveView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render_to_response(
            'bookmarks/bookmark_delete.html',
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):
        """
        Will delete bookmark with a primary key from the url
        or using json data in request.
        """
        if 'bookmark_pk' in kwargs:
            bookmark = get_object_or_404(Bookmark, pk=kwargs['bookmark_pk'])
            bookmark.delete()
            return HttpResponseRedirect(reverse('bookmark_list'))
        else:
            try:
                post_json = json.loads(request.body)
                project = Project.objects.get(slug=post_json['project'])
                version = project.versions.get(slug=post_json['version'])
                url = post_json['url']
                page = post_json['page']
            except KeyError:
                return HttpResponseBadRequest(
                    json.dumps({'error': "Invalid parameters"})
                )

            bookmark = get_object_or_404(
                Bookmark,
                user=request.user,
                url=url,
                project=project,
                version=version,
                page=page
            )
            bookmark.delete()

            return HttpResponse(
                json.dumps({'removed': True}),
                status=200,
                content_type="application/json"
            )

readthedocs/templates/builds/build_detail.html
{% extends "projects/base_project.html" %}

{% load i18n %}
{% load static %}

{% block title %}{{ build.project.name }}{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'builds/js/detail.js' %}"></script>
  <script type="text/javascript">
var detail_views = require('builds/detail');
$(document).ready(function () {
    var view = detail_views.BuildDetailView.init({id: '{{ build.pk }}'});
});
  </script>
{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'builds/css/detail.css' %}" />
{% endblock %}

{% block project_editing %}
  {% with builds_active="active" %}
    {% include "core/project_bar.html" %}
  {% endwith %}
{% endblock %}

{% block content %}
  <div class="build build-detail" id="build-detail">

    <!-- Build meta data -->
    <ul class="build-meta">
      <div data-bind="visible: finished()">
        <li>
          {% trans "Completed" %}
          <span>{{ build.date|date:"N j, Y. P" }}</span>
        </li>

        <li>
          {% trans "Build took" %}
          <span data-bind="text: length">
            {{ build.length }}
          </span>
          {% trans "seconds" %}
        </li>
      </div>

      {% if build.builder and request.user.is_staff %}
        <li>
          {% trans "Built on" %}
          {{ build.builder }}
        </li>
      {% endif %}
    </ul>

    <div class="build-id">
      {% blocktrans with build_id=build.pk %}
        Build #{{ build_id }}
      {% endblocktrans %}
    </div>

    <div class="build-version">
      <span class="build-version-slug">
        {{ build.version.slug }}
      </span>
      <span class="build-commit"
            data-bind="visible: commit">
        (<span data-bind="text: commit">{{ build.commit }}</span>)
      </span>
    </div>

    <div class="build-state">
      <span>
        <span data-bind="visible: !finished(), text: state_display"
              style="display: none;">
          {{ build.get_state_display }}
        </span>
        <img src="{% static 'core/img/loader.gif' %}"
            data-bind="visible: !finished()"
            style="display: none;" />
      </span>
      <span class="build-state-successful"
            data-bind="visible: finished() && success()"
            style="display: none;">
        {% trans "Build completed" %}
      </span>
      <span class="build-state-failed"
            data-bind="visible: finished() && !success()"
            style="display: none;">
        {% trans "Build failed" %}
      </span>
    </div>

    {% if build.output %}
      {# If we have build output, this is an old build #}
      <p>
        <button data-bind="visible: !legacy_output(), click: show_legacy_output">
          {% trans "Show full build output" %}
        </button>
      </p>

      <div data-bind="visible: legacy_output"
           style="display: none;">
        <h3>{% trans "Build Output" %}</h3>
        <pre class="build-output"><span id="build-output">{{ build.output }}</span></pre>

        {% if build.setup %}
          <h3>{% trans "Setup Output" %}</h3>
          <pre class="build-output"><span id="build-setup">{{ build.setup }}</span></pre>
        {% endif %}

        {% if build.setup_error %}
          <h3>{% trans "Environment Standard Error" %}</h3>
          <pre class="build-error"><span id="build-setup_error">{{ build.setup_error }}</span></pre>
        {% endif %}
      </div>

      {% if build.error %}
        <h3>{% trans "Build Errors" %}</h3>
        <pre class="build-error"><span id="build-error">{{ build.error }}</span></pre>
      {% endif %}

    {% else %}
      {# Show new command output if lacking build.output #}

      <div class="build-error"
           data-bind="visible: error"
           style="display: none;">
        <h3>{% trans "Error" %}</h3>
        <p class="build-error"
           data-bind="text: error">
          {{ build.error }}
        </p>
      </div>

      <div id="build-commands"
           class="build-command-list"
           data-bind="visible: commands, foreach: display_commands"
           style="display: none;">
        <div class="build-command"
             data-bind="css: command_status">
          <div class="build-command-run" data-bind="click: toggleCommand">
            <span data-bind="text: command"></span>
          </div>
          <div class="build-command-return"
               data-bind="visible: is_showing">
            <div class="build-command-output">
              <span data-bind="text: output"></span>
            </div>

            <div class="build-command-meta">
              <span class="build-command-time">
                {% trans "Command time:" %}
                <span data-bind="text: run_time">0</span>s
              </span>

              <span class="build-command-exit-code">
                {% trans "Return" %}:
                <span data-bind="text: exit_code"></span>
              </span>
            </div>

          </div>
        </div>
      </div>
    {% endif %}

  </div>
{% endblock %}

readthedocs/templates/builds/build_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% load pagination_tags %}
{% load projects_tags %}

{% block title %}Builds{% endblock %}

{% block project_editing %}
    {% with builds_active="active" %}
        {% include "core/project_bar.html" %}
    {% endwith %}
{% endblock %}

{% block content %}

{% comment %}

<div class="navigable">
<h3>
Filters
</h3>
<ul>
        <form action="" method="get">
            {{ filter.form.as_p }}
            <input type="submit" value="Filter" />
        </form>
</ul>

{% endcomment %}


<!-- BEGIN queue depth warning -->
{% if queue_length > 10 %}
<div>
  <p>
  {% blocktrans with queue_length as queue_length %}
    Whoa! The build queue is {{ queue_length }} tasks long, new builds may take a while.
  {% endblocktrans %}
  </p>
</div>
{% endif %}


<div id="build_list">

        {% autopaginate build_qs 15 %}

        <!-- BEGIN builds list -->
        <div class="module">
          <div class="module-wrapper">

            {% block build_versions %}
            {% if versions %}
            <div class="module-header">
              <div style="float:right;">
                <form method="post" action="{% url "generic_build" project.pk %}">
                  <ul class="build_a_version">
                    <li style="display: inline-block">
                      <input style="display: inline-block" type="submit" value="{% trans "Build Version:" %}">
                    </li>
                    <li style="display: inline-block">
                      <select id="id_version" name="version_slug">
                      {% for version in versions|sort_version_aware %}
                        <option value="{{ version.slug }}">{{ version.slug }}</option>
                      {% endfor %}
                      </select>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
            {% endif %}
            {% endblock %}

              <h1>{% trans "Recent Builds" %}</h1>
            </div>

            <div class="module-list">
              <div class="module-list-wrapper">
                <ul>
                  {% include "core/build_list_detailed.html" %}
                </ul>
              </div>
            </div>

          </div>
        </div>
        <!-- END builds list -->

        {% paginate %}

</div>

{% endblock %}

{% comment %}

{% block extra_scripts %}
{{ block.super }}
  <script type="text/javascript" src="{{ MEDIA_URL }}javascript/build_updater.js"></script>

  <script type="text/javascript">
    $(function() {
      {% for build in active_builds %}
        $('#build-{{ build.id }}').effect('highlight', {}, 3000);
        new BuildListUpdater({{ build.id }}).startPolling();
      {% endfor %}
    });
  </script>
{% endblock %}

{% endcomment %}

readthedocs/templates/builds/tag_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% block title %}{% trans "Popular tags" %}{% endblock %}

{% block content %}
  <ul>
  {% for tag in tag_list %}
    <li><a href="{% url "projects_tag_detail" tag.slug %}">{{ tag.name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}